
#Platter Settings
[general]
	#Item slots for the platter [default: 9]
	#Range: > 0
	platter_slots = 9
	#Radius for the platter to feed [default: 5]
	#Range: 0 ~ 32
	platter_radius = 5
	#Time (in seconds) to wait between platter searches [default: 60]
	#Range: > 0
	platter_period = 60
	#Shall platters render items slightly askew? [default: true]
	platter_eccentricity_enabled = true
	#Should eccentricity be enabled, by how many degrees shall the items render askew each layer? [default: 10]
	#Range: > 0
	platter_eccentricity_value = 10

